# -*- coding: utf-8 -*-
"""email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Gr4avacYlTp1v8FZxQ0gp4jd0UFQJLG
"""

# Upload kaggle.json
from google.colab import files
files.upload()   # Upload your kaggle.json file when prompted

# Set Kaggle API credentials
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download dataset
!kaggle datasets download -d balaka18/email-spam-classification-dataset-csv
!unzip -o email-spam-classification-dataset-csv.zip

print(df.columns.tolist())
print(df.head())

text_column = 'message'  # or whatever your dataset uses

print(df.columns.tolist())    # View actual column names
print(df.head())              # See first few rows
print(df.info())              # Check for non-null entries

text_column = 'message'  # Change this to match your actual column name

print("Non-empty rows:", df[text_column].notnull().sum())

df = pd.read_csv('/content/emails.csv')  # Adjust path if necessary
print(df.head())

# Replace 'message' with your actual column name
df['message'] = df['message'].astype(str)  # Ensure everything is string
df['message'] = df['message'].str.lower().str.strip()  # Lowercase and remove whitespace
df.dropna(subset=['message'], inplace=True)  # Remove any rows with missing text

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
X = vectorizer.fit_transform(df['message'])

print(df.columns.tolist())

df = pd.read_csv('emails.csv')

import pandas as pd

df = pd.read_csv('emails.csv', header=None)

print(df.shape)  # Rows, Columns
print(df.head(1))  # Preview first row

df = pd.read_csv('emails.csv', sep='\t', header=None)
print(df.shape)
print(df.head(1))

import pandas as pd

# Load your CSV as you did
df = pd.read_csv('emails.csv', header=None)

# Combine the comma-separated tokens into normal text
df['text'] = df[0].apply(lambda x: ' '.join(str(x).split(',')))

# Drop the original column
df = df[['text']]

# Check cleaned text
print(df.head(3))

print(df.head(20))
print(df.shape)

import pandas as pd

df = pd.read_csv('emails.csv', low_memory=False)
print(df.head(20))
print(df.columns)
print(df.shape)

!pip install pandas scikit-learn

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Step 3: Load dataset
# Upload your emails.csv file via Colab file upload option
from google.colab import files
uploaded = files.upload()

# Step 4: Read CSV
df = pd.read_csv('emails.csv')

# Step 5: Preprocessing
# Ensure 'text' column is treated as string, fill missing values
X_text = df['text'].fillna("").astype(str)
y = df['spam']  # 1 = Spam, 0 = Not Spam

print(df['text'].head(10))    # Should display real email content
print(df['text'].isnull().sum())  # Should be zero after fillna()

# Assuming your dataset is loaded as 'df'
df['text'] = df['text'].fillna("").astype(str)   # Replace NaN with empty strings

# Optional sanity check:
print(df['text'].apply(len).describe())

df = pd.read_csv('emails.csv')

# Force text data to string (solves your error)
df['text'] = df['text'].fillna("").astype(str)

# Ensure target column exists (change if needed)
print(df['spam'].value_counts())   # Should show counts of 0s and 1s

# Ensure binary labels: 0 (Not Spam), 1 (Spam)
df['spam'] = df['spam'].apply(lambda x: 1 if x != 0 else 0)
print(df['spam'].value_counts())  # Should now show only 0s and 1s

# Convert to binary classification
df['spam'] = df['spam'].apply(lambda x: 1 if x != 0 else 0)

# Convert non-string entries to empty strings
df['text'] = df['text'].astype(str)

# Replace NaNs or missing values
df['text'] = df['text'].fillna('')

# Force convert all entries to string
df['text'] = df['text'].astype(str)

df = df[df['text'].str.strip() != '']

print(df['text'].head(20))

# Keep rows that contain at least one alphabetical character
df = df[df['text'].str.contains('[a-zA-Z]', regex=True)]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['text'])
y = df['spam']

import pandas as pd

# Load the dataset
df = pd.read_csv('emails.csv')

# Display the first few rows of the DataFrame
print(df.head())

# Separate features and target variable
X = df.iloc[:, :-1]  # All columns except the last one
y = df.iloc[:, -1]   # The last column

# Display the shapes of X and y
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

# Train KNN model
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predict using KNN
y_pred_knn = knn.predict(X_test)

# Evaluate KNN
from sklearn.metrics import classification_report, accuracy_score

print("KNN Classification Report:\n", classification_report(y_test, y_pred_knn))
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

print(df.dtypes)

import pandas as pd

# Attempt to convert all columns to numeric
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Check for any remaining non-numeric values
print(df.isnull().sum())

# Fill NaN values with 0 or drop rows with NaN values
df.fillna(0, inplace=True)  # Or use df.dropna(inplace=True)

# Separate features and target variable
X = df.iloc[:, :-1]  # All columns except the last one
y = df.iloc[:, -1]   # The last column

# Display the shapes of X and y
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

# Train KNN model
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predict using KNN
y_pred_knn = knn.predict(X_test)

# Evaluate KNN
from sklearn.metrics import classification_report, accuracy_score

print("KNN Classification Report:\n", classification_report(y_test, y_pred_knn))
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

from sklearn.svm import SVC

# Train SVM model
svm = SVC(kernel='linear', probability=True)
svm.fit(X_train, y_train)

# Predict using SVM
y_pred_svm = svm.predict(X_test)

# Evaluate SVM
print("SVM Classification Report:\n", classification_report(y_test, y_pred_svm))
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))