# -*- coding: utf-8 -*-
"""K-Nearest Neighbors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MsUvgQ3BIyubvNeGdOGd0QeQAUnk1L9
"""

# -----------------------------------------------
# 1. Import Required Libraries
# -----------------------------------------------

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score
)

# -----------------------------------------------
# 2. Load Dataset
# -----------------------------------------------

df = pd.read_csv("diabetes.csv")   # <-- upload this file in Colab
print("Dataset Loaded Successfully!\n")
df.head()

# -----------------------------------------------
# 3. Feature & Target Separation
# -----------------------------------------------

X = df.drop("Outcome", axis=1).values  # features
y = df["Outcome"].values               # target

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

# -----------------------------------------------
# 4. Train-Test Split
# -----------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Set Shape:", X_train.shape)
print("Testing Set Shape:", X_test.shape)

# -----------------------------------------------
# 5. Normalize the Data
# -----------------------------------------------

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Normalization Completed")

# -----------------------------------------------
# 6. Initialize & Train KNN Model
# -----------------------------------------------

knn = KNeighborsClassifier(n_neighbors=5)   # K = 5 (can tune)
knn.fit(X_train, y_train)

print("KNN Model Training Complete")

# -----------------------------------------------
# 7. Predictions
# -----------------------------------------------

y_pred = knn.predict(X_test)

# -----------------------------------------------
# 8. Evaluation Metrics
# -----------------------------------------------

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Error Rate
error_rate = 1 - accuracy

# Precision
precision = precision_score(y_test, y_pred)

# Recall
recall = recall_score(y_test, y_pred)

# Display Results
print("\n===== KNN MODEL RESULTS =====\n")
print("Confusion Matrix:\n", cm)
print(f"\nAccuracy       : {accuracy:.4f}")
print(f"Error Rate     : {error_rate:.4f}")
print(f"Precision      : {precision:.4f}")
print(f"Recall         : {recall:.4f}")